### ISSUE TITLE
when do you plan to release your code

### ISSUE THREAD

**Issue by Zoewayho** [happinesslz/SEED#1]
Thank you for your excellent work. I am very interested in it, when do you plan to release your code?

**Comment by happinesslz** [comment]
@Zoewayho Thanks for your attention! We will release the code before ECCV 2024 conference.

**Comment by Zoewayho** [comment]
I wanna know that how do you design your prediction head when you use your Topk feature to predict K coarse box, i also tried, but the loss of the coarse 3D box would not decrease after reaching a certain threshold. and it appears in the very early stage of training. I have wondered why it works on 2D but not in 3D, but now your works seems that this approach still works on 3D. let me know if it is convenient for you.

**Comment by happinesslz** [comment]
@Zoewayho Hi, we adopt a coarse-to-fine query selection~(Refer to the details of DQS module). Here, maybe you need note the details of the losses in foreground query selection~(coarse queries) and quality query selection~(fine queries) .

**Comment by happinesslz** [comment]
@Zoewayho We have released the official code of SEED.
