### ISSUE TITLE
DGALayer中的自注意力部分是否存在bug？

### ISSUE THREAD

**Issue by CrazyShout** [happinesslz/SEED#4]
作者您好！很荣幸能拜读您的论文，有关您的code中，有一点疑似问题
位置：pcdet/models/model_utils/seed_transformer.py 中的 DGALayer类中您定义了self.self_attn = nn.MultiheadAttention(d_model, nhead)，但是没有指定batch_first=True, 然而您在下方传递qkv时，传入的格式是batch在前，（batch_size, L, E_b）这和您下方的SEEDDecoderLayer中存在的转置操作不一样。我想应该没有在batch之间做注意力的道理？

**Comment by AlmoonYsl** [comment]
@CrazyShout
您好，感谢您提出的问题。经过检查，这里确实是整理代码时出现遗漏，已经将batch_first加入。再次感谢！

**Comment by CrazyShout** [comment]
好的，感谢！
